
import { SupportedLanguage } from './types';

export const LANGUAGES = [
  { code: 'en', name: SupportedLanguage.ENGLISH, flag: '🇺🇸' },
  { code: 'es', name: SupportedLanguage.SPANISH, flag: '🇪🇸' },
  { code: 'zh', name: SupportedLanguage.CHINESE, flag: '🇨🇳' },
  { code: 'fr', name: SupportedLanguage.FRENCH, flag: '🇫🇷' },
  { code: 'de', name: SupportedLanguage.GERMAN, flag: '🇩🇪' },
  { code: 'ja', name: SupportedLanguage.JAPANESE, flag: '🇯🇵' },
  { code: 'ko', name: SupportedLanguage.KOREAN, flag: '🇰🇷' },
  { code: 'pt', name: SupportedLanguage.PORTUGUESE, flag: '🇧🇷' },
  { code: 'ru', name: SupportedLanguage.RUSSIAN, flag: '🇷🇺' },
  { code: 'ar', name: SupportedLanguage.ARABIC, flag: '🇸🇦' },
  { code: 'uk', name: SupportedLanguage.UKRAINIAN, flag: '🇺🇦' },
  { code: 'pl', name: SupportedLanguage.POLISH, flag: '🇵🇱' },
  { code: 'nl', name: SupportedLanguage.DUTCH, flag: '🇳🇱' },
];

export const SYSTEM_INSTRUCTION_BASE = `
You are LingoPop, a cool, witty, and knowledgeable polyglot friend. 
Your goal is to explain words/phrases without sounding like a boring textbook.
Use emojis, keep it punchy, and focus on real-world usage.
`;

// Static suggestions for each target language (to avoid API call)
export const DEFAULT_SUGGESTIONS: Record<string, string[]> = {
  [SupportedLanguage.ENGLISH]: ["Hello", "Love", "Coffee"],
  [SupportedLanguage.SPANISH]: ["Hola", "Amor", "Café"],
  [SupportedLanguage.CHINESE]: ["你好", "爱", "咖啡"],
  [SupportedLanguage.FRENCH]: ["Bonjour", "Amour", "Café"],
  [SupportedLanguage.GERMAN]: ["Hallo", "Liebe", "Kaffee"],
  [SupportedLanguage.JAPANESE]: ["こんにちは", "愛", "コーヒー"],
  [SupportedLanguage.KOREAN]: ["안녕하세요", "사랑", "커피"],
  [SupportedLanguage.PORTUGUESE]: ["Olá", "Amor", "Café"],
  [SupportedLanguage.RUSSIAN]: ["Привет", "Любовь", "Кофе"],
  [SupportedLanguage.ARABIC]: ["مرحبا", "حب", "قهوة"],
  [SupportedLanguage.DUTCH]: ["Hallo", "Liefde", "Koffie"],
  [SupportedLanguage.UKRAINIAN]: ["Привіт", "Любов", "Кава"],
  [SupportedLanguage.POLISH]: ["Cześć", "Miłość", "Kawa"]
};

export const UI_TRANSLATIONS: Record<string, any> = {
  [SupportedLanguage.ENGLISH]: {
    notebook: "Notebook", items: "items", emptyNotebook: "Nothing saved yet!", clear: "Clear", studyMode: "Study Mode", emptyStudy: "Save words to start studying!", goToSearch: "Go to Search", nextCard: "Next Card", tapToFlip: "Tap to flip", tapToFlipBack: "Tap to flip back", definition: "Definition", example: "Example", dictionary: "Dictionary", pronounce: "Pronounce", examples: "Examples", quickTip: "Quick Tip", settings: "Settings", motherTongue: "Mother Tongue", enableImages: "Enable AI Images", enableSfx: "Sound Effects", imageStyle: "Image Style", imageContext: "Image Content", contextTarget: "Target Culture", contextFree: "Free Style", styleFlat: "Flat Design", styleCartoon: "Cartoon", styleGhibli: "Studio Ghibli", styleWatercolor: "Watercolor", stylePixel: "Pixel Art", styleRealistic: "Realistic", historyLabel: "History", greeting: "Modern Dutch Dictionary", suggestionLabel: "Try searching for:", searchPlaceholder: "Type any Dutch word and get meanings + picture + pronunciation", pos: "Part of Speech", plural: "Plural", forms: "Forms", synonyms: "Synonyms", antonyms: "Antonyms", offlineMode: "Offline Mode", offlineError: "You are offline. You can only view saved words.", contactUs: "Contact & Support", contactDesc: "Have questions or suggestions? We'd love to hear from you!", startLearning: "Start Learning", 
    practice: "Practice", listening: "Listening...", micErrorTitle: "Microphone Access", micErrorMsg: "Please check your browser settings to allow microphone access for pronunciation practice."
  },
  [SupportedLanguage.CHINESE]: {
    notebook: "单词本", items: "个词条", emptyNotebook: "还没有保存任何内容！", clear: "清除", studyMode: "学习模式", emptyStudy: "保存单词后开始学习！", goToSearch: "去搜索", nextCard: "下一张", tapToFlip: "点击翻转", tapToFlipBack: "点击翻回", definition: "释义", example: "例句", dictionary: "词典", pronounce: "发音", examples: "例句", quickTip: "小贴士", settings: "设置", motherTongue: "母语", enableImages: "启用 AI 配图", enableSfx: "启用音效", imageStyle: "图片风格", imageContext: "AI 图片内容", contextTarget: "结合文化情景", contextFree: "自由发挥", styleFlat: "扁平风格", styleCartoon: "卡通", styleGhibli: "吉卜力风格", styleWatercolor: "水彩", stylePixel: "像素风", styleRealistic: "写实", historyLabel: "历史记录", greeting: "现代荷兰语大词典", suggestionLabel: "试试搜索：", searchPlaceholder: "输入任意荷兰语单词，获取释义 + 图片 + 发音", pos: "词性", plural: "复数", forms: "变位/变形", synonyms: "同义词", antonyms: "反义词", offlineMode: "离线模式", offlineError: "当前处于离线状态，只能查看已保存的单词。", contactUs: "联系与支持", contactDesc: "如果有问题和建议，欢迎联系我们！", startLearning: "开始学习", 
    practice: "发音练习", listening: "正在听...", micErrorTitle: "麦克风权限", micErrorMsg: "请检查浏览器设置，允许访问麦克风以使用发音练习功能。"
  },
  [SupportedLanguage.SPANISH]: {
    notebook: "Cuaderno", items: "ítems", emptyNotebook: "¡Nada guardado aún!", clear: "Borrar", studyMode: "Modo Estudio", emptyStudy: "¡Guarda palabras para empezar!", goToSearch: "Ir a Buscar", nextCard: "Siguiente", tapToFlip: "Toca para voltear", tapToFlipBack: "Voltear", definition: "Definición", example: "Ejemplo", dictionary: "Diccionario", pronounce: "Pronunciar", examples: "Ejemplos", quickTip: "Consejo", settings: "Ajustes", motherTongue: "Lengua Materna", enableImages: "Imágenes IA", enableSfx: "Efectos de Sonido", imageStyle: "Estilo", imageContext: "Contenido", contextTarget: "Cultura Meta", contextFree: "Estilo Libre", styleFlat: "Plano", styleCartoon: "Dibujos", styleGhibli: "Ghibli", styleWatercolor: "Acuarela", stylePixel: "Pixel", styleRealistic: "Realista", historyLabel: "Historial", greeting: "Diccionario de Neerlandés Moderno", suggestionLabel: "Intenta buscar:", searchPlaceholder: "Escribe una palabra en holandés: significado + imagen + pronunciación", pos: "Categoría", plural: "Plural", forms: "Formas", synonyms: "Sinónimos", antonyms: "Antónimos", offlineMode: "Sin Conexión", offlineError: "Estás desconectado.", contactUs: "Contacto", contactDesc: "¿Preguntas? ¡Escríbenos!", startLearning: "Empezar", 
    practice: "Practicar", listening: "Escuchando...", micErrorTitle: "Acceso al Micrófono", micErrorMsg: "Por favor, permite el acceso al micrófono en la configuración de tu navegador."
  },
  [SupportedLanguage.GERMAN]: {
    notebook: "Notizbuch", items: "Einträge", emptyNotebook: "Noch nichts gespeichert!", clear: "Löschen", studyMode: "Lernmodus", emptyStudy: "Speichere Wörter zum Lernen!", goToSearch: "Zur Suche", nextCard: "Nächste Karte", tapToFlip: "Tippen zum Wenden", tapToFlipBack: "Zurückwenden", definition: "Definition", example: "Beispiel", dictionary: "Wörterbuch", pronounce: "Aussprechen", examples: "Beispiele", quickTip: "Tipp", settings: "Einstellungen", motherTongue: "Muttersprache", enableImages: "KI-Bilder", enableSfx: "Soundeffekte", imageStyle: "Bildstil", imageContext: "Bildinhalt", contextTarget: "Zielkultur", contextFree: "Freistil", styleFlat: "Flach", styleCartoon: "Cartoon", styleGhibli: "Ghibli", styleWatercolor: "Aquarell", stylePixel: "Pixel", styleRealistic: "Realistisch", historyLabel: "Verlauf", greeting: "Modernes Niederländisch-Wörterbuch", suggestionLabel: "Versuche:", searchPlaceholder: "Niederländisches Wort eingeben: Bedeutung + Bild + Aussprache", pos: "Wortart", plural: "Plural", forms: "Formen", synonyms: "Synonyme", antonyms: "Antonyme", offlineMode: "Offline-Modus", offlineError: "Du bist offline.", contactUs: "Kontakt", contactDesc: "Fragen? Kontaktiere uns!", startLearning: "Anfangen", 
    practice: "Üben", listening: "Höre zu...", micErrorTitle: "Mikrofonzugriff", micErrorMsg: "Bitte erlaube den Mikrofonzugriff in deinen Browsereinstellungen."
  },
  [SupportedLanguage.FRENCH]: {
    notebook: "Cahier", items: "mots", emptyNotebook: "Rien d'enregistré !", clear: "Effacer", studyMode: "Mode Étude", emptyStudy: "Enregistrez des mots pour étudier !", goToSearch: "Rechercher", nextCard: "Suivant", tapToFlip: "Retourner", tapToFlipBack: "Retourner", definition: "Définition", example: "Exemple", dictionary: "Dictionnaire", pronounce: "Prononcer", examples: "Exemples", quickTip: "Conseil", settings: "Paramètres", motherTongue: "Langue Maternelle", enableImages: "Images IA", enableSfx: "Effets Sonores", imageStyle: "Style", imageContext: "Contexte", contextTarget: "Culture Cible", contextFree: "Style Libre", styleFlat: "Plat", styleCartoon: "Dessin animé", styleGhibli: "Ghibli", styleWatercolor: "Aquarelle", stylePixel: "Pixel", styleRealistic: "Réaliste", historyLabel: "Historique", greeting: "Dictionnaire Néerlandais Moderne", suggestionLabel: "Essayez :", searchPlaceholder: "Tapez un mot néerlandais : sens + image + prononciation", pos: "Catégorie", plural: "Pluriel", forms: "Formes", synonyms: "Synonymes", antonyms: "Antonymes", offlineMode: "Hors ligne", offlineError: "Vous êtes hors ligne.", contactUs: "Contact", contactDesc: "Des questions ? Contactez-nous !", startLearning: "Commencer", 
    practice: "Pratiquer", listening: "Écoute...", micErrorTitle: "Accès au micro", micErrorMsg: "Veuillez autoriser l'accès au microphone dans les paramètres de votre navigateur."
  },
  [SupportedLanguage.JAPANESE]: {
    notebook: "単語帳", items: "語", emptyNotebook: "まだ保存されていません", clear: "クリア", studyMode: "学習モード", emptyStudy: "単語を保存して学習を始めましょう！", goToSearch: "検索へ", nextCard: "次のカード", tapToFlip: "タップして裏返す", tapToFlipBack: "タップして戻す", definition: "定義", example: "例文", dictionary: "辞書", pronounce: "発音", examples: "例文", quickTip: "ヒント", settings: "設定", motherTongue: "母国語", enableImages: "AI画像", enableSfx: "効果音", imageStyle: "画像スタイル", imageContext: "画像の内容", contextTarget: "現地の文化", contextFree: "フリースタイル", styleFlat: "フラット", styleCartoon: "カートゥーン", styleGhibli: "ジブリ風", styleWatercolor: "水彩", stylePixel: "ドット絵", styleRealistic: "リアル", historyLabel: "履歴", greeting: "現代オランダ語辞書", suggestionLabel: "検索候補:", searchPlaceholder: "オランダ語の単語を入力：意味 + 画像 + 発音", pos: "品詞", plural: "複数形", forms: "活用形", synonyms: "類義語", antonyms: "対義語", offlineMode: "オフライン", offlineError: "オフラインです。保存された単語のみ表示できます。", contactUs: "お問い合わせ", contactDesc: "ご質問・ご提案はこちらまで！", startLearning: "学習を開始", 
    practice: "発音練習", listening: "聞いています...", micErrorTitle: "マイクへのアクセス", micErrorMsg: "ブラウザの設定でマイクへのアクセスを許可してください。"
  },
  [SupportedLanguage.KOREAN]: {
    notebook: "단어장", items: "개", emptyNotebook: "아직 저장된 단어가 없습니다!", clear: "지우기", studyMode: "학습 모드", emptyStudy: "단어를 저장하고 학습을 시작하세요!", goToSearch: "검색으로 이동", nextCard: "다음 카드", tapToFlip: "탭하여 뒤집기", tapToFlipBack: "탭하여 되돌리기", definition: "정의", example: "예문", dictionary: "사전", pronounce: "발음", examples: "예문", quickTip: "팁", settings: "설정", motherTongue: "모국어", enableImages: "AI 이미지", enableSfx: "효과음", imageStyle: "이미지 스타일", imageContext: "이미지 맥락", contextTarget: "문화적 배경", contextFree: "자유 스타일", styleFlat: "플랫", styleCartoon: "카툰", styleGhibli: "지브리 스타일", styleWatercolor: "수채화", stylePixel: "픽셀 아트", styleRealistic: "실사", historyLabel: "기록", greeting: "현대 네덜란드어 사전", suggestionLabel: "추천 검색:", searchPlaceholder: "네덜란드어 단어 입력: 의미 + 이미지 + 발음", pos: "품사", plural: "복수형", forms: "활용형", synonyms: "유의어", antonyms: "반의어", offlineMode: "오프라인", offlineError: "오프라인 상태입니다. 저장된 단어만 볼 수 있습니다.", contactUs: "문의하기", contactDesc: "질문이나 제안이 있으신가요?", startLearning: "시작하기", 
    practice: "연습", listening: "듣고 있습니다...", micErrorTitle: "마이크 접근", micErrorMsg: "발음 연습을 위해 브라우저 설정에서 마이크 접근을 허용해주세요."
  },
  [SupportedLanguage.PORTUGUESE]: {
    notebook: "Caderno", items: "itens", emptyNotebook: "Nada salvo ainda!", clear: "Limpar", studyMode: "Modo Estudo", emptyStudy: "Salve palavras para estudar!", goToSearch: "Ir para Busca", nextCard: "Próximo", tapToFlip: "Toque para virar", tapToFlipBack: "Voltar", definition: "Definição", example: "Exemplo", dictionary: "Dicionário", pronounce: "Pronunciar", examples: "Exemplos", quickTip: "Dica", settings: "Configurações", motherTongue: "Língua Materna", enableImages: "Imagens IA", enableSfx: "Efeitos Sonoros", imageStyle: "Estilo", imageContext: "Contexto", contextTarget: "Cultura Alvo", contextFree: "Livre", styleFlat: "Plano", styleCartoon: "Cartoon", styleGhibli: "Ghibli", styleWatercolor: "Aquarela", stylePixel: "Pixel", styleRealistic: "Realista", historyLabel: "Histórico", greeting: "Dicionário Holandês Moderno", suggestionLabel: "Tente buscar:", searchPlaceholder: "Digite uma palavra em holandês: significado + imagem + pronúncia", pos: "Classe", plural: "Plural", forms: "Formas", synonyms: "Sinônimos", antonyms: "Antônimos", offlineMode: "Offline", offlineError: "Você está offline.", contactUs: "Contato", contactDesc: "Dúvidas? Entre em contato!", startLearning: "Começar", 
    practice: "Praticar", listening: "Ouvindo...", micErrorTitle: "Acesso ao Microfone", micErrorMsg: "Por favor, permita o acesso ao microfone nas configurações do seu navegador."
  },
  [SupportedLanguage.RUSSIAN]: {
    notebook: "Блокнот", items: "слов", emptyNotebook: "Пока ничего нет!", clear: "Очистить", studyMode: "Режим обучения", emptyStudy: "Сохраните слова для начала!", goToSearch: "К поиску", nextCard: "След. карта", tapToFlip: "Нажмите, чтобы перевернуть", tapToFlipBack: "Нажмите, чтобы вернуть", definition: "Определение", example: "Пример", dictionary: "Словарь", pronounce: "Произнести", examples: "Примеры", quickTip: "Совет", settings: "Настройки", motherTongue: "Родной язык", enableImages: "AI Картинки", enableSfx: "Звуковые Эффекты", imageStyle: "Стиль", imageContext: "Контекст", contextTarget: "Культура", contextFree: "Свободный", styleFlat: "Плоский", styleCartoon: "Мультфильм", styleGhibli: "Гибли", styleWatercolor: "Акварель", stylePixel: "Пиксель", styleRealistic: "Реализм", historyLabel: "История", greeting: "Современный голландский словарь", suggestionLabel: "Попробуйте:", searchPlaceholder: "Введите голландское слово: значение + картинка + произношение", pos: "Часть речи", plural: "Мн. число", forms: "Формы", synonyms: "Синонимы", antonyms: "Антонимы", offlineMode: "Оффлайн", offlineError: "Вы оффлайн. Доступны только сохраненные слова.", contactUs: "Контакты", contactDesc: "Есть вопросы? Пишите нам!", startLearning: "Начать", 
    practice: "Практика", listening: "Слушаю...", micErrorTitle: "Доступ к микрофону", micErrorMsg: "Пожалуйста, разрешите доступ к микрофону в настройках браузера."
  },
  [SupportedLanguage.ARABIC]: {
    notebook: "المفكرة", items: "عناصر", emptyNotebook: "لا شيء محفوظ بعد!", clear: "مسح", studyMode: "وضع الدراسة", emptyStudy: "احفظ الكلمات للبدء!", goToSearch: "الذهاب للبحث", nextCard: "التالي", tapToFlip: "انقر للقلب", tapToFlipBack: "انقر للعودة", definition: "التعريف", example: "مثال", dictionary: "القاموس", pronounce: "نطق", examples: "أمثلة", quickTip: "نصيحة سريعة", settings: "الإعدادات", motherTongue: "اللغة الأم", enableImages: "صور AI", enableSfx: "تأثيرات صوتية", imageStyle: "نمط الصورة", imageContext: "محتوى الصورة", contextTarget: "الثقافة المستهدفة", contextFree: "حر", styleFlat: "مسطح", styleCartoon: "كرتون", styleGhibli: "جيبلي", styleWatercolor: "ألوان مائية", stylePixel: "بكسل", styleRealistic: "واقعي", historyLabel: "السجل", greeting: "قاموس هولندي حديث", suggestionLabel: "جرب البحث عن:", searchPlaceholder: "اكتب أي كلمة هولندية: المعنى + الصورة + النطق", pos: "نوع الكلمة", plural: "الجمع", forms: "الأشكال", synonyms: "مرادفات", antonyms: "أضداد", offlineMode: "وضع غير متصل", offlineError: "أنت غير متصل بالإنترنت.", contactUs: "اتصل بنا", contactDesc: "لديك أسئلة؟ تواصل معنا!", startLearning: "ابدأ التعلم", 
    practice: "ممارسة", listening: "استماع...", micErrorTitle: "الوصول إلى الميكروفون", micErrorMsg: "يرجى التحقق من إعدادات المتصفح للسماح بالوصول إلى الميكروفون."
  },
  [SupportedLanguage.UKRAINIAN]: {
    notebook: "Блокнот", items: "слів", emptyNotebook: "Ще нічого не збережено!", clear: "Очистити", studyMode: "Режим навчання", emptyStudy: "Збережіть слова, щоб почати!", goToSearch: "До пошуку", nextCard: "Наступна", tapToFlip: "Натисніть, щоб перевернути", tapToFlipBack: "Натисніть, щоб повернути", definition: "Визначення", example: "Приклад", dictionary: "Словник", pronounce: "Вимовити", examples: "Приклади", quickTip: "Порада", settings: "Налаштування", motherTongue: "Рідна мова", enableImages: "AI Зображення", enableSfx: "Звукові Ефекти", imageStyle: "Стиль", imageContext: "Контекст", contextTarget: "Культура", contextFree: "Вільний", styleFlat: "Плоский", styleCartoon: "Мультфільм", styleGhibli: "Гіблі", styleWatercolor: "Акварель", stylePixel: "Піксель", styleRealistic: "Реалізм", historyLabel: "Історія", greeting: "Сучасний голландський словник", suggestionLabel: "Спробуйте:", searchPlaceholder: "Введіть нідерландське слово: значення + зображення + вимова", pos: "Частина мови", plural: "Мн. число", forms: "Форми", synonyms: "Синоніми", antonyms: "Антоніми", offlineMode: "Офлайн", offlineError: "Ви офлайн. Доступні лише збережені слова.", contactUs: "Контакти", contactDesc: "Є питання? Пишіть нам!", startLearning: "Почати", 
    practice: "Практика", listening: "Слухаю...", micErrorTitle: "Доступ до мікрофона", micErrorMsg: "Будь ласка, дозвольте доступ до мікрофона в налаштуваннях браузера."
  },
  [SupportedLanguage.POLISH]: {
    notebook: "Notatnik", items: "słów", emptyNotebook: "Jeszcze nic nie zapisano!", clear: "Wyczyść", studyMode: "Tryb Nauki", emptyStudy: "Zapisz słowa, aby zacząć!", goToSearch: "Idź do wyszukiwania", nextCard: "Następna", tapToFlip: "Dotknij, aby odwrócić", tapToFlipBack: "Dotknij, aby odwrócić", definition: "Definicja", example: "Przykład", dictionary: "Słownik", pronounce: "Wymów", examples: "Przykłady", quickTip: "Wskazówka", settings: "Ustawienia", motherTongue: "Język ojczysty", enableImages: "Obrazy AI", enableSfx: "Efekty Dźwiękowe", imageStyle: "Styl", imageContext: "Kontekst", contextTarget: "Kultura", contextFree: "Wolny", styleFlat: "Płaski", styleCartoon: "Kreskówka", styleGhibli: "Ghibli", styleWatercolor: "Akwarela", stylePixel: "Piksel", styleRealistic: "Realistyczny", historyLabel: "Historia", greeting: "Nowoczesny Słownik Holenderski", suggestionLabel: "Spróbuj wyszukać:", searchPlaceholder: "Wpisz słowo holenderskie: znaczenie + obraz + wymowa", pos: "Część mowy", plural: "Liczba mnoga", forms: "Formy", synonyms: "Synonimy", antonyms: "Antonimy", offlineMode: "Offline", offlineError: "Jesteś offline. Możesz przeglądać tylko zapisane słowa.", contactUs: "Kontakt", contactDesc: "Masz pytania? Skontaktuj się z nami!", startLearning: "Zacznij", 
    practice: "Ćwicz", listening: "Słucham...", micErrorTitle: "Dostęp do mikrofonu", micErrorMsg: "Sprawdź ustawienia przeglądarki, aby zezwolić na dostęp do mikrofonu."
  },
  [SupportedLanguage.DUTCH]: {
    notebook: "Notitieboek", items: "items", emptyNotebook: "Nog niets opgeslagen!", clear: "Wissen", studyMode: "Studiemodus", emptyStudy: "Sla woorden op om te beginnen!", goToSearch: "Ga naar Zoeken", nextCard: "Volgende Kaart", tapToFlip: "Tik om te draaien", tapToFlipBack: "Tik om terug te draaien", definition: "Definitie", example: "Voorbeeld", dictionary: "Woordenboek", pronounce: "Uitspreken", examples: "Voorbeelden", quickTip: "Snelle Tip", settings: "Instellingen", motherTongue: "Moedertaal", enableImages: "AI-afbeeldingen", enableSfx: "Geluidseffecten", imageStyle: "Afbeeldingsstijl", imageContext: "Afbeeldingsinhoud", contextTarget: "Culturele Context", contextFree: "Vrije Stijl", styleFlat: "Flat Design", styleCartoon: "Cartoon", styleGhibli: "Studio Ghibli", styleWatercolor: "Aquarel", stylePixel: "Pixel Art", styleRealistic: "Realistisch", historyLabel: "Geschiedenis", greeting: "Modern Nederlands Woordenboek", suggestionLabel: "Probeer te zoeken:", searchPlaceholder: "Typ een Nederlands woord: betekenis + afbeelding + uitspraak", pos: "Woordsoort", plural: "Meervoud", forms: "Vormen", synonyms: "Synoniemen", antonyms: "Antoniemen", offlineMode: "Offline Modus", offlineError: "Je bent offline. Je kunt alleen opgeslagen woorden bekijken.", contactUs: "Contact & Ondersteuning", contactDesc: "Vragen of suggesties? Neem contact op!", startLearning: "Beginnen", 
    practice: "Oefenen", listening: "Luisteren...", micErrorTitle: "Microfoon Toegang", micErrorMsg: "Controleer je browserinstellingen om toegang tot de microfoon toe te staan."
  },
};
